# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Unicode-Normalize
version:      1.05
version_from: Normalize.pm
installdirs:  perl
requires:
    bytes:                         0
    Carp:                          0
    constant:                      0
    DynaLoader:                    0
    Exporter:                      0
    File::Copy:                    0
    File::Spec:                    0
    strict:                        0
    Test:                          0
    warnings:                      0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
